name: Build and Push api-music to Docker Hub

on:
  push:
    branches: [ master ]
    paths:
      - 'api-music/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: leighdraws
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api-music
          push: true
          tags: leighdraws/api-music:latest

      - name: Deploy to render
        run: curl https://api.render.com/deploy/srv-d50k1vur433s73dbomr0?key=yfeFk8gjyiY
